### ISSUE TITLE
Error: spawn npm ENOENT in windows 10

### ISSUE THREAD

**Issue by chrismichaelps** [w3cj/create-express-api#1]
Hi CJ,

I have problems installing the dependencies of the repository.
I'm currently using **Windows 10** and **node v10.15.3**

```js
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: spawn npm ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by chrismichaelps** [comment]
I Corrected  the problem by adding the following:
```const npm = which.sync ('npm');```

And changing the following ```'npm', ['install']``` by ```npm, ['install']```
