### ISSUE TITLE
Error when trying to create-express-api

### ISSUE THREAD

**Issue by zsoltgombocz** [w3cj/create-express-api#5]
Hi CJ. I don't know exactly if this repo still alive, or been tested by others, but I looked for this kind of npm package, but unfortunately I am not able to create the folder. I installed it with "npm install -g create-express-api", successfully installed, then with "create-express-api server" got this kind of error: 
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: spawn git ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn git',
  path: 'git',
  spawnargs: [
    'clone',
    'https://github.com/w3cj/express-api-starter.git',
    'server'
  ]
}

Am I doing something wrong? Not the end of the world, but it would be really handy. Also, I am using it via VS Code's Powershell based (?) terminal :)

**Comment by progalex** [comment]
im running in to the same problem... did u find a solution ?

**Comment by zsoltgombocz** [comment]
> im running in to the same problem... did u find a solution ?

Unfortunately not. I simply cloned https://github.com/w3cj/express-api-starter, but if I have time today, I will try to figure out the problem and try to fix it.

**Comment by edwvilla** [comment]
having the same error

```
Cloning into 'name-of-app'...

events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: spawn rm ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:268:19)
    at onErrorNT (internal/child_process.js:468:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:274:12)
    at onErrorNT (internal/child_process.js:468:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn rm',
  path: 'rm',
  spawnargs: [ '-rf', 'name-of-app/.git' ]
}
```

**Comment by samcharles93** [comment]
This error is due to running mac/linux commands on a Windows machine... probably best you just clone the repo 😁
